# Generated by Django 5.1.2 on 2024-11-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
